### ISSUE TITLE
As a user I would like to login to Apache2 by entering a username and password

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-apache#103]
I have checked the tasks, but I did not find a config that configures user authentication using htpasswd for example

**Comment by Christoph-D** [comment]
You can do this by tweaking extra_parameters and manually creating the corresponding .htpasswd file:
````
extra_parameters: |
  <Directory "/var/www/password-protected-directory">
    Require valid-user
    AuthType Basic
    AuthName "Please authenticate"
    AuthUserFile /var/www/password-protected-directory/.htpasswd
  </Directory>
````

It is not a perfect solution, but it works.

If you want to password protect everything, this should work:
````
  <Location "/">
    Require valid-user
    ....
  </Location>
````

**Comment by geerlingguy** [comment]
In addition to what @Christoph-D wrote, see my notes in https://github.com/geerlingguy/ansible-role-apache/pull/63
