### ISSUE TITLE
Add support for conf-enabled/conf-disabled

### ISSUE THREAD

**Issue by dnmvisser** [geerlingguy/ansible-role-apache#114]
There is currently no easy way to disable the default config snippets that are symlinked in `conf-enabled` on Debian/Ubuntu.
Similar functionality is available for `mods-enabled`.

In my specific case I want to change the default log format on Ubuntu, which is configured in `conf-enabled/other-vhosts-access-log.conf`.
If I could disable this snippet, I could add my overriding log format in `apache_global_vhost_settings`.

**Comment by NZSmartie** [comment]
Semi-related. When installing on Ubuntu 16.04.03 LTS I need to post run `a2enconf php*-fpm` to enable PHP. so this would be great to have
