### ISSUE TITLE
apache_vhosts_template is never used and so ignored

### ISSUE THREAD

**Issue by lbarro** [geerlingguy/ansible-role-apache#121]
The apache_vhosts_template documented on the README that should allow to specify a path to a specific template that overrides the default one is never used on the role tasks, instead the default "vhosts.conf.j2" is hard coded as the "src:" value.

Example:

- name: Add apache vhosts configuration.
  template:
    src: "vhosts.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

Should be instead:

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

**Comment by lbarro** [comment]
Was fixed in master branch apparently

**Comment by geerlingguy** [comment]
@lbarro - Does the latest release not contain this fix, or were you just on an older release?

**Comment by lbarro** [comment]
@geerlingguy - Sorry I was on an older release and the latest release contains this fix.
