### ISSUE TITLE
How do you pass the cert files in?

### ISSUE THREAD

**Issue by aram535** [geerlingguy/ansible-role-apache#135]
It would be nice if we could pass in the files via variables rather than having to deploy them first.   
Something like: 

- apache_vhosts_ssl: 
   - servername: foo.com 
      certificate_file: "{{ lookup('file', 'files/cert.crt') }}"
      certificate_key_file: "{{ lookup('file', 'files/cert.key') }}"
      certificate_chain_file: "{{ lookup('file', 'files/chain.key') }}"
....

**Comment by geerlingguy** [comment]
@aram535 - That's not something I want to support in this role directly at this time, as it would add some overhead to what the `apache_vhosts_ssl` currently does. Those cert values should be paths to existing TLS certs on the system.

My most common use case involves installing certbot so I can generate Lets Encrypt certs (with the `--standalone` option, so I don't have to have Apache running half-configured), then I configure Apache to use the certs that were generated.

In other cases, where you have the certs locally and want to install them on the server, it's again recommended to just copy the certs to the server as part of an earlier deployment step.
