### ISSUE TITLE
apache_mods_enabled ignores dependencies (eg for mod_ssl)

### ISSUE THREAD

**Issue by stephankn** [geerlingguy/ansible-role-apache#139]
My experience is based on a Debian/Ubuntu setup.

The naive expectation of the `apache_mods_enabled` configuration variable is that it will function similar to a2enmod, which will typically symlink modules to enable them.

Problem is that for more complex modules this is not sufficient.

In my specific case the ssl module fails to properly load when specifying it as ssl.load like in the example.

a2enmod would also evaluate dependencies listed in ssl.load, resulting in enabling additional modules like socache_shmcb. It would also link the ssl.conf file which brings in required configuration settings.

```
# Depends: setenvif mime socache_shmcb
LoadModule ssl_module /usr/lib/apache2/modules/mod_ssl.so
```

My expectation would be that the role internally use `apache2_module` to enable the roles which takes care of the mentioned specialties.

**Comment by stephankn** [comment]
Please let me know if Debian/Ubuntu is not part of your typical test setup, so I could try to come up with a pull request to address this.

**Comment by stephankn** [comment]
I believe this issue is still recent and the pull request still valid. Is there anythin I can support on moving this forward?

**Comment by stephankn** [comment]
see pull request #193 to fix this issue.

**Comment by MacFlurry** [comment]
can't wait for the merge of your PR :-)

**Comment by stephankn** [comment]
pr is still there. Any issue why not merging?
