### ISSUE TITLE
empty line in top of vhost definition when only defining SSL vhosts

### ISSUE THREAD

**Issue by mhow2** [geerlingguy/ansible-role-apache#148]
With variables defined as below
```
apache_vhosts: []
apache_global_vhost_settings:
apache_vhosts_ssl:
  - servername: xxx...
```

I get the following content in vhosts.conf:
```


<VirtualHost *:443>
  ServerName xxx...
```

So there are empty lines hanging around on the top of the file.

**Comment by geerlingguy** [comment]
Not the worst thing in the world, but it is a little sloppy and would be nice to fix so the file looks more tidy :)
