### ISSUE TITLE
Breaks checking version of Apache

### ISSUE THREAD

**Issue by mhightower** [geerlingguy/ansible-role-apache#149]
I have an Centos 7.3 test server with nothing on it.

Executed
`ansible-playbook --check --user=root --inventory-file inventories/staging/hosts.ini web-server.yml`

TASK [geerlingguy.apache : Get installed version of Apache.] ******************************************************************
fatal: [web01.example.local]: FAILED! => {"changed": false, "cmd": "/usr/sbin/httpd -v", "delta": "0:00:00.003219", "end": "2018-03-19 12:02:24.793169", "msg": "non-zero return code", "rc": 127, "start": "2018-03-19 12:02:24.789950", "stderr": "/bin/sh: /usr/sbin/httpd: No such file or directory", "stderr_lines": ["/bin/sh: /usr/sbin/httpd: No such file or directory"], "stdout": "", "stdout_lines": []}

It just stopped because Apache is not installed yet.

**Comment by geerlingguy** [comment]
Weird... the setup/install tasks run _before_ that task, so Apache should be installed, unless you maybe set `apache_packages` to an empty variable (e.g. `apache_packages: []`)?

**Comment by mhightower** [comment]
You can close this issue. I got around it some how but and most likely it was my mistake and I have forgotten what the solution was.
