### ISSUE TITLE
SSL TLS configurations does not change on server

### ISSUE THREAD

**Issue by ammont** [geerlingguy/ansible-role-apache#152]
I've changed the `apache_ssl_protocol` in vars to: `apache_ssl_protocol: "TLSv1.2"`
But this doesn't change the Apache ssl.conf  on the server. on the server, it still is "SSLProtocol all -SSLv2". My server's OS is Centos 7

**Comment by misilot** [comment]
I believe this is because it only sets it at the VirtualHost level and not system wide.
