### ISSUE TITLE
Error on setup-RedHat.yml when someone put apache_enablerepo in defaults/main.yml with a value of ""

### ISSUE THREAD

**Issue by ericsysmin** [geerlingguy/ansible-role-apache#157]
TASK [geerlingguy.apache : Ensure Apache is installed on RHEL.] **************************************
fatal: [zabbix-server]: FAILED! => {"changed": false, "msg": "Error setting/accessing repos: Error getting repository data for , repository not found"}

Default/main.yml has apache_enablerepo: "" which actually gives it a value so  it causes

---
- name: Ensure Apache is installed on RHEL.
  yum:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_enablerepo | default(omit) }}"

enable repo to have a value of "" which doesn't omit the value.

This should be fixed.

**Comment by ericsysmin** [comment]
Ah, looks like you may have fixed it with `, true` in the master branch

**Comment by geerlingguy** [comment]
@ericsysmin - ha, yep, I was just working on that fix today, related to: https://github.com/ansible/ansible/issues/46517
