### ISSUE TITLE
Is there a configuration field which allows add apache to firewall?

### ISSUE THREAD

**Issue by mrself** [geerlingguy/ansible-role-apache#160]
It would be nice to have configuration field which allows to enable firewall incoming connections for apache.

**Comment by geerlingguy** [comment]
@mrself - I recommend having a separate role for firewall management. For example, you could use `geerlingguy.firewall` and set the following in playbook `vars`:

```yaml
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
```
