### ISSUE TITLE
Add a way to add <IfModule> to httpd.conf

### ISSUE THREAD

**Issue by digitalray** [geerlingguy/ansible-role-apache#169]
I have a need to implement security header injection using          
< IfModule headers_module >
...
< IfModule> 

Currently I do not see extra_parameters option for the httpd.conf file.

**Comment by marzdgzmn** [comment]
> I have a need to implement security header injection using
> < IfModule headers_module >
> ...
> < IfModule>
> 
> Currently I do not see extra_parameters option for the httpd.conf file.

How do you get over configure <IfModule> for the meantime?
I'd like to enable some mods, but I don't seem to see any variable supporting it though.
