### ISSUE TITLE
Service module does not work in containers

### ISSUE THREAD

**Issue by p1rateg0ld** [geerlingguy/ansible-role-apache#172]
I was using your role as an example for testing with Molecule, but the very last task in your play checks that httpd is running and the service isn't compatible with docker

**Comment by ezbik** [comment]
I'd understand about LXC, but Ansible in Docker? Aren't you doing something wrong way?

**Comment by p1rateg0ld** [comment]
Molecule is for testing ansible roles. The default driver and quickest solution uses docker to provision a host and run the playbook against it. I'd like to continue using docker instead of Vagrant.

I see that geerlingguy uses docker for his testing and I'm trying to figure out how he achieves this.

**Comment by geerlingguy** [comment]
Note that I am using my own Docker images which have systemd running inside, so I can test services using the `service` module. See my Molecule configuration here: https://github.com/geerlingguy/ansible-role-apache/blob/master/molecule/default/molecule.yml

Note, however, that I _also_ use this role to build Apache inside containers, and in that sort of environment it's anathema to run an init system inside; Apache should be pid 1. So for that use case, it is best to do what I do here: https://github.com/geerlingguy/php-apache-container

But I may be able to make this even better by skipping that task if neither service state or enabled are set to `true` (the latter of which is not currently configurable!).
