### ISSUE TITLE
AWS ALB 21 second load with "SSLCipherSuite AES256+EECDH:AES256+EDH"

### ISSUE THREAD

**Issue by ElijahLynn** [geerlingguy/ansible-role-apache#174]
Not sure why but this line I grabbed from the defaults and used in our vhosts for implementing this role and it is causing a very consistent 20 second (21 second actually) load time from an Amazon ALB (same cert attached). I commented it out and the whole connection flies. I am wondering if the ALBs don't support that ciphersuite combo?

Figured I would  post here to get it talked about.

**Comment by zain-ggj** [comment]
Did u any further with this @ElijahLynn ?

**Comment by ElijahLynn** [comment]
> Did u go any further with this @ElijahLynn ?

Yeah, just removed the `SSLCipherSuite AES256+EECDH:AES256+EDH` in the vhosts file, all is working well now for HTTPS.
