### ISSUE TITLE
Not able to specify user or group to run Apache

### ISSUE THREAD

**Issue by Aethylred** [geerlingguy/ansible-role-apache#175]
The module currently does not allow changing the account that the Apache service runs as.

I think these are set in the default conf file:

RHEL/CentOS: /etc/httpd/conf/httpd.conf
Ubuntu/Debian: /etc/apache/conf/apache.conf

It looks like it could be done by feeding more regexs into `apache_ports_configuration_items` but I think switching to a template would be prefereable.

**Comment by Aethylred** [comment]
Using mod_privileges in vhost definitions would also work: 
https://httpd.apache.org/docs/2.4/mod/mod_privileges.html

**Comment by Aethylred** [comment]
Also using SuexecUserGroup as an extra parameter works, but can be unreliable for web services that redirect to other parts of the filesystems (like UserDir)

**Comment by Aethylred** [comment]
I've tries adding a custom `apache_ports_configuration_items` as a host variable, but it seems this is overridden by the OS variables, so makes no changes.

**Comment by Aethylred** [comment]
Right, whatever variables set in your playbook are overwritten when the var files are loaded in:
https://github.com/geerlingguy/ansible-role-apache/blob/master/tasks/main.yml#L35

**Comment by hectoralicea** [comment]
Has there been anymore thought on this?
It's my understanding that services such as apache httpd should never run as root.
This issue will trigger a number of critical vulnerabilities in our security scanning software.
