### ISSUE TITLE
Set apache user to have a login shell

### ISSUE THREAD

**Issue by ElijahLynn** [geerlingguy/ansible-role-apache#178]
`cat /etc/passwd` == `apache:x:48:48:Apache:/var/www:/sbin/nologin`

Which means SSHing in you have to run commands as `sudo --user apache bash -c "drush status" etc. And for that to work you have to export a new PATH etc. 

Either we should improve docs around this or set the `apache` user to have a login shell that has PATH set to use system commands such as composer and the drush launcher etc.

**Comment by jonpugh** [comment]
I think what's really needed is a standard "application" user role, as it's not really secure to give access to the apache user.

See this rare "Canonical Question" on StackExchange: https://serverfault.com/questions/357108/what-permissions-should-my-website-files-folders-have-on-a-linux-webserver

> ## Maintained by a group of users
> If more than one user is responsible for maintaining the site, you will need to create a group to use for assigning permissions. It's good practice to create a separate group for each website, and name the group after that website.

The "Aegir Project" was designed like this from it's inception, except it uses one user for all the websites: The `aegir` user is put into the `www-data` group, all web files are owned by `aegir`, in `www-data` group... It also has in code, a standard secure user ownership/permissions model for drupal.

I created the `aegir-user` role on ansible galaxy to reproduce the setup the Aegir Project uses, which standardizes an ownership/permissions scheme.  https://github.com/opendevshop/ansible-role-aegir-user/blob/master/tasks/main.yml

This is still kind-of an aegir specific hack I think. Now that we have the provision-ops group, I want to create our first basic role: a "web-app-user" role that does exactly what `opendevshop/aegir-user` does but with a generic name, and that works with @geerlingguy 's roles.

**Comment by jonpugh** [comment]
Here's the config that results from Aegir's `drush provision-verify` command:

```sh
-r--r-----  1 aegir apache    173 Aug 14 19:41 aegir.services.yml
-r--r-----  1 aegir aegir  209514 Aug 14 19:41 drushrc.php
drwxrws--- 13 aegir apache   4096 Aug 19 16:25 files
drwxrwsr-x  2 aegir aegir    4096 Jul 30 23:37 libraries
-r--r-----  1 aegir apache     28 Jul 30 23:37 local.settings.php
drwxrwsr-x  4 aegir aegir    4096 Jul 31 17:27 modules
drwxrws---  5 aegir apache   4096 Jul 30 23:37 private
-r--r-----  1 aegir apache   5673 Aug 14 19:41 settings.php
drwxrwsr-x  2 aegir aegir    4096 Jul 30 23:37 themes
```
