### ISSUE TITLE
custom SSL port is not working when SSL port is used by another process.

### ISSUE THREAD

**Issue by anasjaghoub** [geerlingguy/ansible-role-apache#196]
OS: Ubuntu 20.04

Use case: I have Nginx is installed on the same server as a reverse proxy, and I have the apache configured to run on port 8080 with SSL. when trying to start it fails due to on port.conf SSL port is 443. 

I noticed that in port.conf the port 8080 is added successfully, but 443 still the same and does not take the value provided for  apache_listen_port_ssl.

**Comment by gabor-nagy-stylers** [comment]
same issue
