### ISSUE TITLE
possibility to enabled OR not apache on boot

### ISSUE THREAD

**Issue by jayalpes** [geerlingguy/ansible-role-apache#209]
In tasks/main.yml:
- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: **"{{ apache_boot }}"**
Can you add a var to enabled or not on boot ?

**Comment by nhojpatrick** [comment]
@jayalpes does this PR cover your requirements https://github.com/geerlingguy/ansible-role-apache/pull/217?

Not sure if or when it will get merged in as struggling to get some improvements merged in for vhosts and proxies for about 6 months.
