### ISSUE TITLE
should the role create the documentroot path on the filesystem?

### ISSUE THREAD

**Issue by raidoh** [geerlingguy/ansible-role-apache#234]
should the role create the documentroot path on the filesystem or should we do this our self with another task?
For now it does not create the Directory on the filesystem - i guess this is by design?

Thanks in advance.

**Comment by geerlingguy** [comment]
This role assumes the directory already exists (e.g. another task or role sets up the application / web directories before this role runs.

**Comment by raidoh** [comment]
thank you - just wanted to make sure i've done nothing wrong. Thanks for everything you do :)
