### ISSUE TITLE
Apache is ignoring DirectoryIndex set via apache_global_vhost_settings in vhosts.conf

### ISSUE THREAD

**Issue by websafe** [geerlingguy/ansible-role-apache#242]
Hello,

I've noticed that on Debian 11 Apache is ignoring the first line in `vhosts.conf`:

```
DirectoryIndex index.php index.html
```

and

```
DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm
```

from `/etc/apache2/mods-enabled/dir.conf` takes precedence.

So when a directory contains `index.html` and `index.php` the `index.html` is being served every time, despite having `DirectoryIndex index.php index.html` in `vhosts.conf`.

When I move the `DirectoryIndex index.php index.html`  in `vhosts.conf` into `<VirtualHost *:80>...</VirtualHost>` or `<VirtualHost *:443>...</VirtualHost>` everything behaves as expected.

Or maybe I'm doing something wrong?

**Comment by JonasPammer** [comment]
According to [the official documentation](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#DirectoryIndex) this is expected behaviour:

> Multiple DirectoryIndex directives within the [same context](https://httpd.apache.org/docs/2.4/sections.html) will add to the list of resources to look for rather than replace
