### ISSUE TITLE
Best way to add multiple lines via apache_vhosts extra_parameters

### ISSUE THREAD

**Issue by danbohea** [geerlingguy/ansible-role-apache#27]
I'd like to add the following multiple lines via the `apache_vhosts`'s `extra_parameters` property:

```
<Directory "{{ path_to_docroot}}">
    Options FollowSymLinks Indexes
    AllowOverride All
</Directory>
```

What's the best way to go about doing this given that it's multiple lines with indentation?

**Comment by JorisVanEijden** [comment]
I did mine like this:
`extra_parameters: '{{ "\n" }}  ErrorLog "|/usr/sbin/rotatelogs -l /var/www/virtual/default/logs/error_%Y%m%d.log 86400"{{ "\n" }}  CustomLog "|/usr/sbin/rotatelogs -l /var/www/virtual/default/logs/access_%Y%m%d.log 86400" combined{{ "\n" }}'`

Very ugly, but it works.
I'd love to hear a better way.

**Comment by TonnyXu** [comment]
I ended up with simple string like this:

```
        extra_parameters: "RailsEnv production\n  ErrorLog ${APACHE_LOG_DIR}/http.app.com-error.log\n  CustomLog ${APACHE_LOG_DIR}/http.app.com.log combined"
```

**Comment by geerlingguy** [comment]
See also: https://github.com/geerlingguy/ansible-role-nginx/issues/20

**Comment by TonnyXu** [comment]
@geerlingguy Oh! That's great! thanks!

**Comment by rossedman** [comment]
@TonnyXu :+1:

**Comment by geerlingguy** [comment]
Please see the updated example in the README, about the use of `extra_parameters` in an `apache_vhosts` block.
