### ISSUE TITLE
Allow for virtualhost without documentroot

### ISSUE THREAD

**Issue by miloskroulik** [geerlingguy/ansible-role-apache#28]
I would like to make a virtualhost only to redirect to completely different domain. Would it be possible to make documentroot property optional, so I will be able to create vhost like this?

````
<VirtualHost *>
  ServerName www.example.com
  Redirect 301 / http://example.com/
</VirtualHost>
````
Thanks for consideration.

**Comment by geerlingguy** [comment]
Added!
