### ISSUE TITLE
apache_listen_port_ssl doesn't affect the ports.conf

### ISSUE THREAD

**Issue by louim** [geerlingguy/ansible-role-apache#29]
Hello,

It seems like that changing the `apache_listen_port_ssl` doesn't change the ports.conf file.

This line: https://github.com/geerlingguy/ansible-role-apache/blob/d687bb21c58b0227a4ea0e59b0c2cf431e74b146/vars/apache-24.yml#L6
works only for `apache_listen_port`.

I think a `ports.conf` file template would be the best for this.

**Comment by t2d** [comment]
would be fixed by #78

**Comment by tobias-richter** [comment]
Nearly three years later, please have a look at https://github.com/geerlingguy/ansible-role-apache/pull/150. 
I hope that @geerlingguy will review and merge it...

**Comment by t2d** [comment]
In the meantime, I have started to use https://github.com/systemli/ansible-role-apache24. It only supports Debian-based OS.
