### ISSUE TITLE
Allow disabling of listening for ssl.

### ISSUE THREAD

**Issue by louim** [geerlingguy/ansible-role-apache#30]
Currently, it's impossible to disable the listening of port 443 for ssl. You can change it (not fully, see #29), but it's impossible to disable it completely. My use-case is doing SSL termination at the load balancer level, so I dont need apache listening on a port for SSL.

**Comment by geerlingguy** [comment]
Sounds reasonable; I'll try to fix this soon.

**Comment by t2d** [comment]
Would be possible with https://github.com/geerlingguy/ansible-role-apache/pull/78

**Comment by okgolove** [comment]
Any chances it will be merged?

**Comment by okgolove** [comment]
Noooooooo

**Comment by Sispheor** [comment]
Any news on this?

**Comment by Sispheor** [comment]
Also, it seems that changing the ssl port doesn't work.
```
apache_listen_port_ssl: 5443 
```

The file is still configured to use 443.

**Comment by Sispheor** [comment]
Because the file `/etc/httpd/conf.d/ssl.conf` is never updated.
I'm on Centos 8
