### ISSUE TITLE
"Ensure Apache is started and enabled on boot" rule prevents fixing Apache configuration

### ISSUE THREAD

**Issue by wizonesolutions** [geerlingguy/ansible-role-apache#31]
This rule always fails the playbook when the Apache configuration following a previous failed run is in an error state, since if a task that came after `geerlingguy.apache` messes up the Apache configuration, this rule will always error out when it tries to start it. I'm not sure of the best way to solve this; perhaps a configuration parameter that will ignore errors if set? Then one could set that, fix the errors, and then unset it — a sort of development configuration, if you will.

Otherwise, I have to do a destroy/up cycle whenever I screw up the Apache configuration :) Of course, I guess I could just comment out the role, let it fix itself, and then comment it back in, but yeah...thought I'd open an issue to discuss.

**Comment by geerlingguy** [comment]
I typically just destroy the VM and rebuild if borked too badly, or log in and tweak the file to stop the bleeding, then re-run the playbook... but it might be better to figure out a way to do all the configuration prior to the task that ensures Apache is started / enabled on boot instead.

**Comment by geerlingguy** [comment]
Closing in favor of #46 — that PR/fix should allow you to get out of this situation by changing that variable to `stopped`. I'll try to get to it ASAP.
