### ISSUE TITLE
No information about how add extra params to general apache config

### ISSUE THREAD

**Issue by ArtemProkopenko** [geerlingguy/ansible-role-apache#33]
For example. I had installed mod_dumpio and I want to turn it on. I have to add following lines to config, but It is not obvious how i can do it.
```php
DumpIOInput On
DumpIOOutput On
DumpIOLogLevel debug
```

**Comment by geerlingguy** [comment]
See #27 for more discussion on this - Closing this issue as a duplicate.

**Comment by ArtemProkopenko** [comment]
I'm talking about global parameters.

**Comment by geerlingguy** [comment]
I see... the best way to do that would be to add a simple `xyz.conf` file to the directory where Apache automatically includes extra configuration—and do this in your own playbook somewhere after the role completes, with a `notify: restart apache` tacked on. Check your `httpd.conf` for the path to the includes (it differs between RHEL/Debian).
