### ISSUE TITLE
vagrant up fails - on apache2 install `/var/www/html.dpkg-new': Operation not permitted

### ISSUE THREAD

**Issue by stuzzo** [geerlingguy/ansible-role-apache#35]
Hi,
I get this error as stated also here -> https://github.com/geerlingguy/drupal-vm/issues/85.

These are my synced_folder settings:

    config.vm.synced_folder ".",  "/vagrant", id: "vagrant-root", :nfs => true
    config.vm.synced_folder "../../../../project", "/var/www", id: "application",  :nfs => true

I'm working on an Ubuntu 12.04 (64 bit) and I'm trying to setup a Virtualbox precise 64 box.

Thank you

**Comment by geerlingguy** [comment]
Please see:

  - https://github.com/puphpet/puphpet/issues/990
  - https://github.com/puphpet/puphpet/wiki/Shared-Folder:-Permission-Denied
  - https://github.com/puphpet/puphpet/issues/810

It looks like it's a permissions issue, likely only occurring in VirtualBox with certain settings. One thing you might want to try is setting the synced folder to something other than `/var/www` (maybe try a subdirectory in there instead?).
