### ISSUE TITLE
Allow installing mpm-worker

### ISSUE THREAD

**Issue by gbirke** [geerlingguy/ansible-role-apache#4]
While this package can be used to install the mpm-worker version, it seems not very elegant to me:
- On Debian, you have to provide your own `apache_packages` list, making it incompatible to future changes to the default package list.
- On RedHat you have to modify `/etc/sysconfig/httpd` in a separate task.

Maybe you can build in a config variable and configure the mpm type in the tasks.

**Comment by wizonesolutions** [comment]
+1. ` apache_packages` isn't documented in the default variables. I found it while reading the source code.

**Comment by wizonesolutions** [comment]
Now I'm setting up a CentOS server and found I wanted the same thing. Do you know offhand what would be required for CentOS? A `lineinfile` task? Maybe I can take a stab...
