### ISSUE TITLE
Fail after complete DrupalVM upgrade

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-apache#44]
Symptom:

```
TASK: [geerlingguy.apache | Include OS-specific variables.] *******************
fatal: [20150831123758.loc.gbuild.net] => Failed to template {% if drupalvm_webserver == 'apache’ %} True {% else %} False {% endif %}: template error while templating string: unexpected char u"'" at 28
```

Task causing symptom:

```
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
```

Files referred from symptom:

```
---
apache_daemon: apache2
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/apache2
apache_conf_path: /etc/apache2

__apache_packages:
  - apache2
  - apache2-utils

apache_ports_configuration_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }

```

It's a Debian 12.04 system using Ansible 1.9.3, and I'm not able to update any of the systems I'm working on until this can be resolved, or I try and change it all over to NGINX.

**Comment by fubarhouse** [comment]
I'm going to try to diagnose this further before it gets looked at.

**Comment by geerlingguy** [comment]
@fubarhouse - Thanks for opening the issue—looks like you got it resolved? There's a new configuration variable in `example.config.yml`, `drupalvm_webserver`, that needs to be configured. Probably should've put out a little more warning, but it's at least noted in the Drupal VM 2.1.0 release notes.

**Comment by fubarhouse** [comment]
@geerlingguy I haven't resolved this yet... I will definitely let you know when though - it's very important to me that I get around this one way or another. Also yeah the variables were set as expected, I'll be migrating a lot of websites for launch within the next 36 hours so once I get a bit of down-time I'll be working on this :)

**Comment by geerlingguy** [comment]
@fubarhouse - Ah, I just noticed:

```
{% if drupalvm_webserver == 'apache’ %}
```

It looks like a unicode character snuck in there somewhere. That's not from my code, is it??

**Comment by fubarhouse** [comment]
Interesting, thanks for the notes!

For the record, the configuration file at the root contains `drupalvm_webserver: apache` and so that's where the variable is coming from. I noticed the unicoding problem, but I haven't looked into why exactly.

Whatever the case, if the solution is applicable to others it would be worthwhile knowing about it.

**Comment by fubarhouse** [comment]
@geerlingguy I've managed to get around the problem by replacing

- { role: geerlingguy.apache, when: drupalvm_webserver == 'apache' }
- { role: geerlingguy.nginx, when: drupalvm_webserver == 'nginx' }

with 
```
- { role: geerlingguy.apache, when: drupalvm_webserver == "apache" }
- { role: geerlingguy.nginx, when: drupalvm_webserver == "nginx" }
```

I'm not sure why, but it doesn't like string literals.
I don't mind if you use this knowledge or not - all that matters to me is my want to keep things updated as I need or as cool things come out and this exercise has been fun - I don't actually know how many people consistently reprovision their drupalvm systems - the ones using the system I've made are a bit more specialized.

Honestly when coding var == "" should always beat var == '' always unless you use var == "''" to prevent string literals. For example you can't print variables in bash with echo '$var' as it prints $var - and echo "$var" prints the value of $var
This is ultimately your call, but you should know this in case more show up with this problem.
