### ISSUE TITLE
Ensure Apache is started should be optional

### ISSUE THREAD

**Issue by pgilad** [geerlingguy/ansible-role-apache#45]
This also relates to https://github.com/geerlingguy/ansible-role-apache/issues/36

If I have missing directories (as DocumentRoot) and also if I hadn't copied my ssl certificates, starting apache will fail.

I want to run my setup-task after apache was installed (to have the correct default configs and dirs) and not have to setup directories and ssl before.

Can we make this optional? I can add a PR if needed

**Comment by leifmadsen** [comment]
Funny enough I just ran into this exact same issue! I looked at the pull request and it looks legit. Going to try and apply it locally and I'll report back shortly. Thanks!

**Comment by geerlingguy** [comment]
@leifmadsen - Any further info?

**Comment by leifmadsen** [comment]
Sorry for not responding back. I had applied the pull request locally and have been testing, and all is well. It's been working so well that I actually totally forgot we had a locally patched version of the role :)
