### ISSUE TITLE
Specify loaded mods?

### ISSUE THREAD

**Issue by hrstoyanov** [geerlingguy/ansible-role-apache#49]
Thanks for the good Ansible roles (both MySQL and Apache)!
Question: How can one specify loaded modules for Apache. I need PHP module and AJP (for Java) configured in my Apache proxy.

**Comment by geerlingguy** [comment]
From the readme:

```
apache_mods_enabled:
  - rewrite.load
  - ssl.load
apache_mods_disabled: []
```

This currently only works on Debian/Ubuntu platforms, though; for other platforms, you'll need to enable or disable the mods separately at this time.

**Comment by hrstoyanov** [comment]
Jeff,
To clarify my question: how do I configure module stuff like these:
```
LoadModule proxy_module /opt/jboss/httpd/lib/httpd/modules/mod_proxy.so
LoadModule proxy_ajp_module /opt/jboss/httpd/lib/httpd/modules/mod_proxy_ajp.so
LoadModule slotmem_module /opt/jboss/httpd/lib/httpd/modules/mod_slotmem.so
LoadModule manager_module /opt/jboss/httpd/lib/httpd/modules/mod_manager.so
LoadModule proxy_cluster_module /opt/jboss/httpd/lib/httpd/modules/mod_proxy_cluster.so
LoadModule advertise_module /opt/jboss/httpd/lib/httpd/modules/mod_advertise.so
```

Looking at the vhost-2.4.conf.j2, there is nothing to help me witht his. 
See section 2.3  here:
http://docs.jboss.org/mod_cluster/1.3.0/html_single/#d0e276

**Comment by hrstoyanov** [comment]
Maybe we need something like this added into the template:
```
{# Load modules#}
{% for apache_module in apache_modules %}
  LoadModule {{ apache_module}}.name  {{apache_module}}.location
```
where ```apache_modules``` can be defaulted to an empty array?

**Comment by geerlingguy** [comment]
@hrstoyanov - Which OS/platform are you deploying on?

**Comment by kzap** [comment]
Same here, there is no way in this role to enable modules and set configuration from them, it all has to be ad-hoc outside of this role
