### ISSUE TITLE
Changes in DirecotryIndex are not populated to vhost file

### ISSUE THREAD

**Issue by krisdante** [geerlingguy/ansible-role-apache#59]
I changed the value in my own variable but on server it is still default one

Centos 7

My value in group_vars/web.yml

```
apache_mods_enabled:
  - rewrite.load
apache_global_settings: |
  DirectoryIndex index.html index.phtml
```

**Comment by geerlingguy** [comment]
Do you have `apache_global_settings` set in any other variables files in your playbook? If you set the variable inside a `vars` section or in a file included in `vars_files`, it will overwrite the vars you set in `group_vars`.

**Comment by geerlingguy** [comment]
Closing this out; please let me know if this is still an issue.
