### ISSUE TITLE
Set dockerfile via variable to allow for multiple OS versions

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-apache#61]
#60 Added the ability to test against the latest Ubuntu and latest CentOS releases, but I no longer have the roles tested on the n-1 release. I want that feature back so I can at least test on Ubuntu 12 and CentOS 6 too.

**Comment by bertvv** [comment]
Take a look here: https://github.com/bertvv/ansible-role-apache/tree/fix/61

Added Ubuntu 12.04 Dockerfile and updated the .travis.yml file to also take the distro version into account. It worked locally, the test also runs on Travis CI. https://travis-ci.org/bertvv/ansible-role-apache/builds/96643383

**Comment by geerlingguy** [comment]
@bertvv - totally understand :)

For some reason I was making the same changes (at least AFAICR), but they were failing on the docker build command... maybe I had a typo.

I've switched to explicitly adding the dockerfile name, as that makes it easier for me to distinguish between _Dockerfile_, _tag_, and _general OS version_.

**Comment by geerlingguy** [comment]
Spent a little more time researching things; it looks like it might not be as possible as I'd hoped to do CentOS 6 testing: https://github.com/docker/docker/issues/13297

Regardless, being able to test on 3/4 supported OSes is about a jillion times better than 1/4 :)

**Comment by bertvv** [comment]
As far as I understood the issue, it's about EL6 as a Docker *host*. EL6 is pre-systemd, so the "install systemd" trick from the Centos7 Dockerfile is not needed here. I created a new Dockerfile with that part stripped and added an env: entry for CentOS 6. Build result here: https://travis-ci.org/bertvv/ansible-role-apache/builds/96682780 

.travis.yml:

```Yaml
  - distribution: centos
    version: 6
    init: /sbin/init
    run_opts: ""
    container_id: $(mktemp)
```

Dockerfile.centos-6:

```
FROM centos:6
RUN yum -y update; yum clean all;
RUN yum -y install epel-release
RUN yum -y install git ansible sudo
RUN yum clean all
# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers
# Install Ansible inventory file
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts
CMD ["/usr/sbin/init"]
```

Cool, eh? :-D

**Comment by geerlingguy** [comment]
Dangit... I had tried that, but it wasn't working for me. Must be pre-Christmas inability to get stuff working :P
