### ISSUE TITLE
Override config files

### ISSUE THREAD

**Issue by jyoungs** [geerlingguy/ansible-role-apache#68]
It would be great if I could override the template files from the playbook. Something like this, but optional:

```
-    src: "vhosts-{{ apache_vhosts_version }}.conf.j2"
+    src: "{{playbook_dir}}/templates/vhosts-{{ apache_vhosts_version }}.conf.j2"
```

**Comment by geerlingguy** [comment]
In this case, you can just set `apache_create_vhosts` to `false`, then you can manage the vhosts file(s) however you'd like in your playbook that uses this role. For more advanced/complicated vhosts, I usually just do that.
