### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by daviespaul** [geerlingguy/ansible-role-apache#70]
Hi - I am new to git (and Linux) and Ansible (and devops)!

I have cloned this git and copied the files to my home on Centos7

If I run ansible-playbook main.yml --ask-sudo-pass in the tasks directory I get the error 'include_vars is not a legal parameter of an Ansible Play'

I assume I am doing something fundamentally wrong here. I also cannot see where it is picking up any hosts from. Any help appreciated. Thanks

**Comment by geerlingguy** [comment]
Can you run `ansible --version` and see what version you have?

Also, if you're just getting into Ansible (and devops), you might want to have a look at my book, http://www.ansiblefordevops.com/ :)

My guess is you'll need to create a new Ansible playbook, and include this role from _there_—see as an example: https://github.com/geerlingguy/ansible-vagrant-examples/blob/master/lamp/provisioning/playbook.yml

**Comment by daviespaul** [comment]
Hi Guy - I have 1.9.4 - I have your book but I'm trying to run before I can walk I think.

**Comment by geerlingguy** [comment]
haha, yeah; you should have a read through chapter 4 and chapter 6 to understand how playbooks work and how roles (like this one) encapsulate some of the tasks in a playbook in a reusable way.
