### ISSUE TITLE
where is the vhosts.conf file?

### ISSUE THREAD

**Issue by babatundebusari** [geerlingguy/ansible-role-apache#80]
I see you mentioned **_vhosts.conf_** file but I can't find that file or see how it should like in the repo.
Where do i find the **_vhosts.conf_** file or how should it look like?

Thanks

**Comment by babatundebusari** [comment]
anyone willing to help with this? i can't see any vhosts.conf file on the repo; would be great to at least have a dummy vhosts.conf file so one is not confused

thanks

**Comment by geerlingguy** [comment]
They're both located inside the `templates` directory: https://github.com/geerlingguy/ansible-role-apache/tree/master/templates

**Comment by babatundebusari** [comment]
but that is **vhosts-2.2.conf.j2** and not **vhosts.conf**

Here on line 8
you mentioned "vhosts.conf"

https://github.com/geerlingguy/ansible-role-apache/blob/master/defaults/main.yml

That is what is confusing, should that be instead any of the template file and NOT **vhosts.conf** but **vhosts-2.2.conf.j2** or **vhosts-2.4.conf.j2** ?

Thanks

**Comment by geerlingguy** [comment]
This role uses one of two different templates—one for Apache 2.2, another for Apache 2.4—and saves that vhost template to a file of the name specified by `apache_vhosts_filename`. So that variable is only to indicate what you want the generated vhosts filename to be.

**Comment by geerlingguy** [comment]
See, for example: https://github.com/geerlingguy/ansible-role-apache/blob/master/tasks/configure-RedHat.yml#L16
