### ISSUE TITLE
Add option to delete default vhosts on Redhat/CentOS as well

### ISSUE THREAD

**Issue by anisse** [geerlingguy/ansible-role-apache#81]
There are default vhosts and configuration files in CentOS 7:
- autoindex.conf
- userdir.conf
- welcome.conf

(source: http://mirror.centos.org/centos/7/os/x86_64/Packages/httpd-2.4.6-40.el7.centos.x86_64.rpm )

At least welcome.conf will provide a file if a configured vhost has no /index.html. Maybe something should be done to cleanup these config files ?

**Comment by geerlingguy** [comment]
This functionality should be triggered by `apache_remove_default_vhost` set to `true`. I need to check the contents of those files and make sure they're all safe to discard by default, though. I've only been using Nginx on RHEL 7, so I didn't notice those files sneak into the default package install :/

**Comment by anisse** [comment]
Yes, it should use the same option. Indeed, a careful review of the files might be needed, as I just gave them a quick glance before deleting on my server.

**Comment by dspolleke** [comment]
This issue is still relevant.  removing userdir.conf welcome.conf and autoindex.conf is needed!

**Comment by pixelrebel** [comment]
I'm probably doing something wrong, but it seems like this role relies on the ssl.conf default vhost config to enable the `LISTEN 443` directive.  When that file is removed, there is no other place in the configuration where that `LISTEN 443` exists, even if you define an SSL virtualhost in `apache_vhosts_ssl`.  Am I supposed to leave the ssl.conf file in place?  When I do, the generic self signed certs take priority.

**Comment by Blackskyliner** [comment]
We need to keep the default ssl.conf file and comment most directly vHost related configuration within `<VirtualHost _default_:443>` and this VirtualHost definition itself off the file via regex pattern. But keep general settings which would also make sense in a global scope e.G. `SSLHonorCipherOrder` and the "Engine Options" or "Protocol Adjustments".

This way there should be no breakage for ssl on COS/RHEL related systems.

**Comment by nitharsandvag** [comment]
Hello @geerlingguy 

we are facing the same problem with default ssl.conf and VirtualHost entry on our Redhat System, are you going to merge the changes from @Blackskyliner ?
I have tested the code locally and it is working fine.

**Comment by Blackskyliner** [comment]
Related, autoclosed PR here: https://github.com/geerlingguy/ansible-role-apache/pull/237
