### ISSUE TITLE
Allow specification of Directory directives

### ISSUE THREAD

**Issue by hamish** [geerlingguy/ansible-role-apache#82]
I'd like to be able to modify the items in the vhost Directory section.

My motivation is that I'm having problems where small changes to files hosted on a virtualbox shared folder are not being reflected through Apache.

This appears to be due to broken sendfile support in VirtualBob shared folders.
https://frankooh.wordpress.com/2011/01/21/vboxsf-and-small-files/
https://www.virtualbox.org/ticket/9069

As a workaround - I'd like to Disable SendFile and MMAP in my dev environments. Currently, I've simply edited a local copy of my role template, however it would be better to be able to define directives on a group_var by group_var basis.

<Directory "{{ vhost.documentroot }}">
    EnableSendfile Off
    EnableMMAP Off
    AllowOverride All
    Options -Indexes FollowSymLinks
    Order allow,deny
    Allow from all
  </Directory>

I'm happy to build the patch and submit it if you prefer, but also happy if you prefer to write the code yourself.

thanks!

**Comment by hamish** [comment]
I realized that my use case can be accomplished globally by setting the option in apache_global_vhost_settings. 
I'll leave this open but I now feel it's low priority.

**Comment by geerlingguy** [comment]
Sorry about not responding earlier; some recent role changes should make this simpler—you can either override the entire template file, or add some other directives now which can make this simpler.
