### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by xylodev** [geerlingguy/ansible-role-apache#90]
I am using this role to manage my dev env, which is a mix of Debian and FreeBSD hosts. Unfortunately, it lacks FreeBSD support, which seems to be used more often than eg. Solaris.

For my own needs I added FreeBSD-specific tasks to this role. Would you be interested in including FreeBSD support? I can take care of keeping it up-to-date.

**Comment by geerlingguy** [comment]
I would be willing to add FreeBSD support as long as it can be added similar to the other supported OSes (e.g. everything specific to FreeBSD in its own file).
