### ISSUE TITLE
CentOS 7 has Apache 2.4.6 in repos

### ISSUE THREAD

**Issue by patkar** [geerlingguy/ansible-role-apache#91]
but the `vars/RedHat.yml` references 2.2

**Comment by geerlingguy** [comment]
I think it's actually overridden (correctly) by https://github.com/geerlingguy/ansible-role-apache/blob/master/vars/apache-24.yml, because I have a task that will check the currently-installed version to make sure the right vhosts are used.

**Comment by patkar** [comment]
Upsi, sorry :grin:
