### ISSUE TITLE
serveralias is a single value

### ISSUE THREAD

**Issue by dnmvisser** [geerlingguy/ansible-role-apache#98]
As it says on the tin.
It is very common to have more than one `ServerAlias`, which is not possible to express using the `serveralias` variable at the moment as that is a string.
I'm working around it by configuring my own var which is a list,  then loop over it in `extra_parameters`:

```
# host vars
- serveraliases:
  - alias1.example.org
  - alias2.example.org
  - alias3.example.org

# apache config
apache_vhosts:
  - servername: main.example.org
extra_parameters: |
  {% for serveralias in serveraliases %}
    ServerAlias {{ serveralias }}
  {% endfor %}
```

**Comment by geerlingguy** [comment]
Can't you have multiple values in one ServerAlias directive? I haven't needed to do it, but I thought that's how that value worked. If not, we can do something like what you propose in the template.

**Comment by dnmvisser** [comment]
Hi
I just discovered this as well, this sits in templates/vhosts.conf.j2:

{% if vhost.serveralias is defined %}
  ServerAlias {{ vhost.serveralias }}
{% endif %}


If that would iterate over a list that'd fix things.
Probably needs some backward compatibility check to still allow a single string.

thanks

Dick

**Comment by geerlingguy** [comment]
The way it currently works, you can just stick multiple aliases with a space separating them. Another option you can use (if you already have all the aliases in a list, and want them to be a string) is to set the variable like `serveralias: {{ mylistofaliases | join(' ') }}`.

I'd rather not change the role to allow lists added directly here.
